=== yuarja/cse445-a4/NationalParks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="NationalParks">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="NationalPark" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string"/>
              <xs:element name="Phone" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
              <xs:element name="Address">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Number" type="xs:integer"/>
                    <xs:element name="Street" type="xs:string"/>
                    <xs:element name="City" type="xs:string"/>
                    <xs:element name="State" type="xs:string"/>
                    <xs:element name="Zip" type="xs:integer"/>
                  </xs:sequence>
                  <xs:attribute name="NearestAirport" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="rating" use="optional">
              <xs:simpleType>
                <xs:restriction base="xs:double">
                  <xs:minInclusive value="1"/>
                  <xs:maxInclusive value="5"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== yuarja/cse445-a4/NationalParksErrors.xml
<NationalPark xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://yuarja.github.io/cse445-a4 NationalParks.xsd">
  <NationalPark rating="4.8">
    <Name>Yosemite National Park</Name>
    <Phone>209-372-0200</Phone>
    <Address NearestAirport="Fresno Airport">
      <Number>9035</Number>
      <Street>Village Drive</Street>
      <City>Yosemite National Park</City>
      <State>CA</State>
      <Zip>95389</Zip>
    </Address>
  </NationalPark>
  <NationalPark rating="4.8">
    <Name>Yosemite National Park</Name>
    <Phone>209-372-0200</Phone>
    <Address NearestAirport="Fresno Airport">
      <Number>9035</Number>
      <Street>Village Drive</Street>
      <City>Yosemite National Park</City>
      <State>CA</State>
      <Zip>95389</Zip>
    </Address>
  </NationalPark>
  <NationalPark rating="4.8">
    <Name>Yosemite National Park</Name>
    <Phone>209-372-0200</Phone>
    <Address NearestAirport="Fresno Airport">
      <Number>9035</Number>
      <Street>Village Drive</Street>
      <City>Yosemite National Park</City>
      <State>CA</State>
      <Zip>95389</Zip>
    </Address>
  </NationalPark>
  <NationalPark rating="4.8">
    <Name>Yosemite National Park</Name>
    <Phone>209-372-0200</Phone>
    <Address NearestAirport="Fresno Airport">
      <Number>9035</Number>
      <Street>Village Drive</Street>
      <City>Yosemite National Park</City>
      <State>CA</State>
      <Zip>95389</Zip>
    </Address>
  </NationalPark>
  <NationalPark rating="4.8">
    <Name>Yosemite National Park</Name>
    <Phone>209-372-0200</Phone>
    <Address NearestAirport="Fresno Airport">
      <Number>9035</Number>
      <Street>Village Drive</Street>
      <City>Yosemite National Park</City>
      <State>CA</State>
      <Zip>95389</Zip>
    </Address>
  </NationalPark>
  <NationalPark rating="4.8">
    <Name>Yosemite National Park</Name>
    <Phone>209-372-0200</Phone>
    <Address NearestAirport="Fresno Airport">
      <Number>9035</Number>
      <Street>Village Drive</Street>
      <City>Yosemite National Park</City>
      <State>CA</State>
      <Zip>95389</Zip>
    </Address>
  </NationalPark>
  <NationalPark rating="4.8">
    <Name>Yosemite National Park</Name>
    <Phone>209-372-0200</Phone>
    <Address NearestAirport="Fresno Airport">
      <Number>9035</Number>
      <Street>Village Drive</Street>
      <City>Yosemite National Park</City>
      <State>CA</State>
      <Zip>95389</Zip>
    </Address>
  </NationalPark>
  <NationalPark rating="4.8">
    <Name>Yosemite National Park</Name>
    <Phone>209-372-0200</Phone>
    <Address NearestAirport="Fresno Airport">
      <Number>9035</Number>
      <Street>Village Drive</Street>
      <City>Yosemite National Park</City>
      <State>CA</State>
      <Zip>95389</Zip>
    </Address>
  </NationalPark>
  <NationalPark rating="4.8">
    <Name>Yosemite National Park</Name>
    <Phone>209-372-0200</Phone>
    <Address NearestAirport="Fresno Airport">
      <Number>9035</Number>
      <Street>Village Drive</Street>
      <City>Yosemite National Park</City>
      <State>CA</State>
      <Zip>95389</Zip>
    </Address>
  </NationalPark>
  <NationalPark rating="4.8">
    <Name>Yosemite National Park</Name>
    <Phone>209-372-0200</Phone>
    <Address NearestAirport="Fresno Airport">
      <Number>9035</Number>
      <Street>Village Drive</Street>
      <City>Yosemite National Park</City>
      <State>CA</State>
      <Zip>95389</Zip>
    </Address>
  </NationalPark>
</NationalParks>
